<!DOCTYPE html>
<html>
<head>
	<title>Responses</title>
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<!-- Material Design Bootstrap -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.7/css/mdb.min.css" rel="stylesheet">

	<style type="text/css">
		.container {
			background-color: white;
			border-radius: 10px;
			margin-top: 20px;
			margin-bottom: 20px;
			padding-bottom: 20px;
		}

		.padding {
			padding-top: 20px;
			padding-bottom: 20px;
		}

		body {
			padding-top: 50px;
			background-color: lightblue;
		}
	</style>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-12 text-center padding">
				<h1>Responses</h1>
			</div>
			<div class="col-12 col-md-6 padding">
				<h4>Responses by Gender</h4>
				<canvas id="chartGender"></canvas>
			</div>
			<div class="col-12 col-md-6 padding">
				<h4>How satisfied were you with the attendant?</h4>
				<canvas id="chartQ1"></canvas>
			</div>
			<div class="col-12 col-md-6 padding">
				<h4>How satisfied were you with the timeliness of your service?</h4>
				<canvas id="chartQ2"></canvas>
			</div>
			<div class="col-12 col-md-6 padding">
				<h4>How satisfied were you with the results?</h4>
				<canvas id="chartQ3"></canvas>
			</div>
		</div>
	</div>

	<!-- JQuery -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<!-- Bootstrap tooltips -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
	<!-- Bootstrap core JavaScript -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
	<!-- MDB core JavaScript -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.7/js/mdb.min.js"></script>

	<script type="text/javascript">
		// QUESTION 1
		var ctx = document.getElementById("chartGender").getContext('2d');
		var myChart = new Chart(ctx, {
			type: 'pie',
			data: {
				labels: ["M", "F"],
				datasets: [{
					label: '# of Votes',
					data: [<?= $genderM ?>, <?= $genderF ?>],
					backgroundColor: ['lightblue','pink']
				}]
			}
		});

		// QUESTION 1
		var ctx = document.getElementById("chartQ1").getContext('2d');
		var myChart = new Chart(ctx, {
			type: 'bar',
			data: {
				labels: ["1", "2", "3", "4", "5"],
				datasets: [{
					label: '# of Votes',
					data: [<?= $attendant1 ?>, <?= $attendant2 ?>, <?= $attendant3 ?>, <?= $attendant4 ?>, <?= $attendant5 ?>],
					backgroundColor: ['cyan','lightblue','lightgreen','orange','pink']
				}]
			}
		});

		// QUESTION 1
		var ctx = document.getElementById("chartQ2").getContext('2d');
		var myChart = new Chart(ctx, {
			type: 'bar',
			data: {
				labels: ["1", "2", "3", "4", "5"],
				datasets: [{
					label: '# of Votes',
					data: [<?= $timeliness1 ?>, <?= $timeliness2 ?>, <?= $timeliness3 ?>, <?= $timeliness4 ?>, <?= $timeliness5 ?>],
					backgroundColor: ['cyan','lightblue','lightgreen','orange','pink']
				}]
			}
		});

		// QUESTION 1
		var ctx = document.getElementById("chartQ3").getContext('2d');
		var myChart = new Chart(ctx, {
			type: 'bar',
			data: {
				labels: ["1", "2", "3", "4", "5"],
				datasets: [{
					label: '# of Votes',
					data: [<?= $results1 ?>,<?= $results2 ?>,<?= $results3 ?>,<?= $results4 ?>,<?= $results5 ?>],
					backgroundColor: ['cyan','lightblue','lightgreen','orange','pink']
				}]
			}
		});
	</script>
</body>
</html>