<!DOCTYPE html>
<html>
<head>
	<title>Demographics</title>
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<!-- Material Design Bootstrap -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.7/css/mdb.min.css" rel="stylesheet">

	<style type="text/css">
		.container {
			background-color: white;
			border-radius: 10px;
			margin-top: 20px;
			margin-bottom: 20px;
			padding-bottom: 20px;
		}

		.padding {
			padding-top: 20px;
			padding-bottom: 20px;
		}

		body {
			padding-top: 50px;
			background-color: lightblue;
		}
	</style>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-12 text-center padding">
				<h1>Demographics</h1>
			</div>
			<div class="col-12 col-md-6 padding">
				<form action="/demographics/save" method="get">
					<div class="form-group">
						<label for="name">What is your name?</label>
						<input type="text" class="form-control" id="name" name="name" placeholder="Type your name" required>
					</div>

					<div class="form-group">
						<label for="age">What is your age?</label>
						<input type="number" class="form-control" min="16" max="120" id="age" placeholder="Type a number from 16 to 120" name="age" required>
					</div>

					<div class="form-group">
						<label for="gender">What is your gender?</label>
						<select class="form-control" name="gender" id="gender" required>
							<option value="">Please select</option>
							<option value="M">Male</option>
							<option value="M">Female</option>
						</select>
					</div>

					<div class="text-center">
						<button type="submit" class="btn btn-outline-dark">Continue</button>
					</div>
				</form>
			</div>

			<div class="d-none d-md-block col-md-6 padding">
				<img class="img-fluid img-thumbnail" src="https://s3-eu-central-1.amazonaws.com/centaur-wp/marketingweek/prod/content/uploads/2016/09/13101405/demographic-segmentation-behaviour.jpg" alt="Demographics">
			</div>
		</div>
	</div>
</body>
</html>